title:            Matt
tagline:          A beautiful theme.
description:      This page is about me
canonical: http://jekyll.gtat.me

# Owner/author information
owner:
  name:           Matthew Mansat
  avatar:         avatar.png
  bio:            "Aspiring Teacher"
  email:          mtmansat@gmail.com
  twitter:        
  github:         mansat
  instagram:      
  dribbble:       
  disqus:         balzac
  location:       "Berkeley, California"
  # Plug in your disqus shortname!

tools:
  standards:      "HTML, SCSS, Jekyll"
  software:       "git"

# Links to include in top navigation
# For external links add external: true
links:
  - title: About
    url: /about
  - title: Github
    url: https://github.com/mansat
    external: true
  - title: Matt
    url: https://mansat.github.io
    external: true

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    America/Los_Angeles
future:      true
highlighter: pygments
markdown:    kramdown

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false

  coderay:
    coderay_line_numbers:
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

sass:
    style: :compressed

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp"]
